### ISSUE TITLE
Spark 3.1.2 support does not work with protobuf (sparksql-scalapb)

### ISSUE THREAD

**Issue by RayRoestenburg** [lightbend/cloudflow-contrib#35]
Trying out a spark project with protobuf, when the executor runs:
```
Caused by: java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.readStringRequireUtf8()Ljava/lang/String;
	at sensors.proto.Data$.parseFrom(Data.scala:140)
	at sensors.proto.Data$.parseFrom(Data.scala:126)
	at scalapb.GeneratedMessageCompanion.parseFrom(GeneratedMessageCompanion.scala:185)
	at scalapb.GeneratedMessageCompanion.parseFrom$(GeneratedMessageCompanion.scala:185)
	at sensors.proto.Data$.parseFrom(Data.scala:126)
	at cloudflow.streamlets.proto.ProtoCodec.$anonfun$decode$1(ProtoCodec.scala:27)
```
Probably because of many protobuf libs on the classpath, 
looking at sparksql-scalapb, hadoop contains an outdated protobuf library that needs to be shaded:
https://scalapb.github.io/docs/sparksql/#setting-up-your-project
https://github.com/thesamet/sparksql-scalapb-test/blob/master/build.sbt
But cloudflow does not use sbt-assembly, so we need to find another way to ensure that the right protobuf library is used.
(could also have another reason, but we should be able to see from dependencies)
Should probably try https://github.com/coursier/sbt-shading to shade the dependencies.

**Comment by debasishg** [comment]
Does this example work with Cloudflow `2.2.0` + Spark `3.1.2` + Avro ?

**Comment by debasishg** [comment]
shading should fix it .. https://stackoverflow.com/a/41609653/16405999

**Comment by debasishg** [comment]
Tried to shade the module as per https://scalapb.github.io/docs/sparksql/ but ran into https://github.com/scalapb/ScalaPB/issues/1122 ..

**Comment by andreaTP** [comment]
@debasishg , after further investigation the result is:
 - we can't use `protobuf-java` 2.5.0 since ScalaPB doesn't support it and we are using relevant code
 - shading is, really, the only option
 
 taking a look at what you did, probably the missing steps to hack together something are:
  - remove all the libraries explicitly, since they are going to be included in the jar, e.g.:
  ```
  extraDockerInstructions := Seq(
      Instructions.Run.shell(Seq("rm", "/opt/cloudflow/*.jar"))
   ),
  ```
  - add back the generated uber-jar in `/opt/cloudflow` and rename it `/opt/cloudflow/cloudflow-runner.jar`
  
  __if__ the resulting Docker image works we can cleanup the process.

**Comment by debasishg** [comment]
@andreaTP also spark cannot work with `protobuf-java` `3.5.x` - hence I guess  the only option is to ..

* shade `protobuf-java` within `scalapb` so that it uses the shaded version
* let spark use the `2.5.0` version (it uses APIs which are incompatible with `3.5.x`
* not sure what version `akka-grpc` needs though - will have to check

Hence I don't think we can delete all versions other than `3.5.x`

**Comment by andreaTP** [comment]
@debasishg all good but:

> Hence I don't think we can delete all versions other than 3.5.x

We strictly _have to_ remove all versions but `2.5.0`, which is the one used by Spark itself, 3.X will be shaded in the resulting application artifact and be used by `akka-grpc`, scalapb and Cloudflow.

**Comment by debasishg** [comment]
@andreaTP Ok, so I shaded `akka-protobuf` as well, so that it also uses `3.15.8`, which it requires. The problem is if I keep only `2.5.0` unshaded, the protobuf compiler complains of missing class ..
```
Compiling 2 protobuf files to /Users/debasishghosh/lightbend/cloudflow-contrib/examples/spark-sensors-proto/target/scala-2.12/akka-grpc/main
[error] java.lang.NoClassDefFoundError: com/google/protobuf/compiler/PluginProtos$CodeGeneratorRequest
```

**Comment by andreaTP** [comment]
> The problem is if I keep only 2.5.0 unshaded, the protobuf compiler complains of missing class ..

You probably need an extra step, move the compilation of protobuf files to a separate sub-project, depends on the artifact, and shade the proto dependency.

**Comment by debasishg** [comment]
Here's the latest status on this ..

After lots of attempts I figured out that the only way to achieve the goal is to do the following steps:

* shade rules for `protobuf-java` (version `3.15.8`) coming from `scalapb` 
* shade rules for `protobuf-java` (version `3.15.8`) coming from `akka-protobuf` 
* shade rules for other sources of `protobuf-java` for any version other than `2.5.0`
* prepare an assembly of _all_ jars _except Spark_ so that all instances of `protobuf-java` v `3.15.8` are shaded and their transitive dependencies changed accordingly. This will result in an uber-jar + the Spark jars
* use `dependencyOverride` to base the version of `protobuf-java` to `2.5.0`, the one that Spark uses

This implies a redesign of how we package the image in cloudflow today for spark plugin. This is a significant effort I think. Should we invest time and effort on this ? @RayRoestenburg @andreaTP

**Comment by RayRoestenburg** [comment]
This should be retried with 0.2.0, which upgrades to Spark 3.2.0. Closing this ticket for that reason.
